### ISSUE TITLE
Error while running scripts/play/play_real_corridor_env.py

### ISSUE THREAD

**Issue by jacobjj** [braincorp/bc-gym-planning-env#13]
While running the play_real_corridor_env.py I get the following error:
`Traceback (most recent call last):
  File "play_real_corridor_env.py", line 16, in <module>
    _, path, test_maps = get_random_maps_squeeze_between_obstacle_in_corridor_on_path()
  File "/root/code/bc-gym-planning-env/bc_gym_planning_env/envs/rw_corridors/tdwa_test_environments.py", line 52, in get_random_maps_squeeze_between_obstacle_in_corridor_on_path
    original_costmap = CostMap2D.from_state(pickle.load(f))
  File "/opt/conda/envs/bc_gym/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
`
Any suggestions on how to resolve this ?

Thanks

**Comment by olegsinyavskiy** [comment]
@jacobjj which python version do you use? we might have not tested this specific function with python 3..

**Comment by olegsinavski** [comment]
@jacobjj , thanks for letting me know. Its related to python 3 usage. Do you mind using python2.7 while we are fixing it?

**Comment by tigerwlin** [comment]
bug fix PR opened for this issue:
https://github.com/braincorp/bc-gym-planning-env/pull/15
